version: "3"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  api: &api_test
    build:
      context: ./Api/
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./Api/src:/myapp
      - ./Api/src/vendor/bundle:/myapp/vendor/bundle
    ports:
      - "3001:3000"
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    depends_on:
      - db
