FROM ruby:2.7

ENV RAILS_ENV=production

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
  && apt-get update -qq \
  && apt-get install -y nodejs yarn
  
RUN mkdir /myapp

WORKDIR /myapp
COPY ./src /myapp
RUN bundle config --local set path 'vendor/bundle' \
  && bundle install